### ISSUE TITLE
Silkscreen reference, and Fab value relative position

### ISSUE THREAD

**Issue by Ziemnianin007** [MitjaNemec/PlaceFootprints#2]
Hey,
at first I would like to thank you for effort in making and sharing such improvement I've been looking in new kicad version. As i've been copying footprints on my schema I noticed that text from silkscreen reference and Fab value are alligned at default position after copying, not that which have been manually chosen by hand (also size of those is not updated). It creates much manually work in multiple sheets alignments because you have to place each component texts by hand.

From smaller not so important issues: 
By default kicad uses "," in variables not "." which makes some confusion in X, Y position input.
If last used X,Y, arrangement type, sheets to replicate (if available), hierarchy level values would be remembered it would be very beneficial in work speed. 
Also multiple component selection from same subschema would make work faster. Even doing each selected component arrangement by opening edition window one by one would be beneficial in design speed. Also clicking Ok by enter would be faster.
With all those features you add tick to make those steps automatically (if possible) to all selected components, and subsheet footprint copying is automated :) (button for selecting all footprint from schema would make it even faster). Those are just my thougths about the topic.

Thank you for this plugin
![Screenshot_757](https://user-images.githubusercontent.com/22123166/149758067-a363dbc5-07bd-44b9-8734-8229434483a1.png)
![Screenshot_756](https://user-images.githubusercontent.com/22123166/149758083-7e6d9c46-5017-46ab-9369-b9c5ec987bc5.png)
!

**Comment by MitjaNemec** [comment]
Thanks for reporting the issues. There are two issues I'll address:

1. replication of footprint text. I'll add this as an option
2. proper handling of decimal separator

As for speeding up your replication of layout between multiple channels (e.g. rooms) I have a plugin that solves this. But you'll either have to wait so that I port [ReplicateLayout](https://github.com/MitjaNemec/Kicad_action_plugins#replicate-layout) plugin to PCM in v6. Or if you are impatient you can try using the version from 5.99_test branch

**Comment by Ziemnianin007** [comment]
Thanks for addressing selected issues. I've been consider implementation of proposed solutions by myself, but if you have written it in order versions and in future you would like to port it, I will abandon this idea. Thanks for your wonderful job.

**Comment by MitjaNemec** [comment]
Well, I've managed to release a fix, so you can update and test the plugin
