### ISSUE TITLE
Plugin does not work on 6.99

### ISSUE THREAD

**Issue by AiGreek** [MitjaNemec/PlaceFootprints#6]
Hey, it's been a while :D

I installed this morning the latest version of your plugin via github (and the pcm afterwards) then, the last version of Kicad Nightly and I find myself with this error : 

![image](https://user-images.githubusercontent.com/16197044/152821399-5803c020-4b56-467a-b5b9-1e7fe7c052e4.png)

```
Application: KiCad PCB Editor (64-bit)

Version: (6.99.0-818-g79c7d55a40), release build

Libraries:
	wxWidgets 3.1.5
	FreeType 2.11.0
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Feb  6 2022 21:40:25
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

Any idea ?

**Comment by MitjaNemec** [comment]
Yes. 6.99 has significant changes in python API. I am only supporting the plugins to work on 6.0.x

**Comment by AiGreek** [comment]
ow okey, i'll wait then or try hard to do a little fork. Thanks for the answer ;)

**Comment by MitjaNemec** [comment]
You'll wait a while, as I'll start supporting 6.99 when V7 is going to be close to release or slightly after.
You can try to [fix](https://github.com/MitjaNemec/PlaceFootprints/issues/1#issuecomment-1013846845) this yourself.

**Comment by AiGreek** [comment]
I finally updated this plugin to work with the last nightly.

```
Application: KiCad PCB Editor (64-bit)

Version: (6.99.0-2176-g69f25f35a8), release build

Libraries:
	wxWidgets 3.1.7
	FreeType 2.11.1
	HarfBuzz 4.2.0
	FontConfig 2.14.0
	libcurl/7.83.1-DEV Schannel zlib/1.2.12

Platform: Windows 11 (build 22000), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jun 17 2022 07:52:05
	wxWidgets: 3.1.7 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.83.1-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

```

It was indeed just a lot of fp.fp.SetPosition(pcbnew.VECTOR2I(pcbnew.wxPoint(*new_position))) to paste.
Works like a charm now !
