### ISSUE TITLE
Plugin does not work on 6.0.2

### ISSUE THREAD

**Issue by majsterElektron** [MitjaNemec/PlaceFootprints#8]
Hi, 
I just updated KiCad to 6.0.2 and your plugin stopped working.

When I select footprint and hit plugin button there is error 'Property not found: Sheetfile'

```
Application: KiCad

Version: 6.0.2, release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.81.0 OpenSSL/1.1.1m-fips zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.46.0 OpenLDAP/2.4.59

Platform: Linux 5.16.8-1-default x86_64, 64 bit, Little endian, wxGTK, KDE, x11

Build Info:
	Date: Feb 11 2022 00:00:00
	wxWidgets: 3.1.5 (wchar_t,STL containers) GTK+ 3.24
	Boost: 1.78.0
	OCC: 7.5.3
	Curl: 7.81.0
	ngspice: 36
	Compiler: GCC 11.2.1 with C++ ABI 1016

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

```

**Comment by MitjaNemec** [comment]
Thanks for reporting this.

Can you elaborate a bit more on this. Did the plugin work in 6.0.1 or 6.0.0 with the same project? Is this a project you've created with 6.0.x?

Can you attach `place_footprints.log` file, which should be in the project folder?

**Comment by majsterElektron** [comment]
Yes, downgraded to 6.0.1 and it worked again. Project created in 6.0.x.

Log was rewritten so I upgraded back to 6.0.2 and it works now. Weird.

**Comment by MitjaNemec** [comment]
The issue might be the same as https://github.com/MitjaNemec/ReplicateLayout/issues/10.

Code has been fixed, but it will take while for the new release to become available in PCM.

**Comment by MitjaNemec** [comment]
Assuming the issue is solved
